//! Handles completion requests for the language server.

use tower_lsp::lsp_types::{
    CompletionItem, CompletionItemKind, CompletionResponse, CompletionTextEdit, Documentation,
    InsertTextFormat, MarkupContent, MarkupKind, Position, Range, TextEdit,
};

use crate::{
    rms::{self, CompletionText},
    server::lookup_hover,
};

// Generated by build.rs from data/completions.toml.
// Defines: static COMPLETABLE_TOKENS: &[CompletableToken]
include!(concat!(env!("OUT_DIR"), "/completions.rs"));

/// A token that can be offered as a completion suggestion.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct CompletableToken {
    /// The display label shown in the completion popup, with correct casing.
    label: &'static str,
    /// The lowercase version of the label, used for case-insensitive matching.
    lower: &'static str,
    /// The kind of token, used for coloring and icons in the completion popup.
    kind: CompletionItemKind,
    /// The snippet to insert when the completion is accepted, or `None` if the
    /// label should be inserted as-is. Uses LSP snippet syntax where `${N:placeholder}`
    /// marks tab stops and `$0` marks the final cursor position.
    snippet: Option<&'static str>,
}

impl CompletableToken {
    /// Creates a `CompletionItem` for this token.
    /// When the completion is accepted, `range` is replaced with the token's
    /// snippet if one exists, or the label otherwise.
    fn to_completion_item(&self, range: Range) -> CompletionItem {
        CompletionItem {
            label: self.label.to_string(),
            kind: Some(self.kind),
            insert_text_format: self.snippet.map(|_| InsertTextFormat::SNIPPET),
            text_edit: Some(CompletionTextEdit::Edit(TextEdit {
                range,
                new_text: self.snippet.unwrap_or(self.label).to_string(),
            })),
            documentation: lookup_hover(self.label).map(|doc| {
                Documentation::MarkupContent(MarkupContent {
                    kind: MarkupKind::Markdown,
                    value: doc.to_string(),
                })
            }),
            ..Default::default()
        }
    }
}

/// Returns the completable tokens matching the given completion text.
///
/// First attempts to match against the full token. If no matches are found,
/// falls back to matching against the prefix up to the cursor position.
/// This ensures that partially typed tokens that don't yet match anything
/// still surface relevant completions based on what has been typed so far.
///
/// For example, if the user types `create_xyz` with the cursor after `create_`,
/// the full token `"create_xyz"` matches nothing, but the prefix `"create_"`
/// matches all `create_` commands.
fn filter_tokens(completion_text: &CompletionText) -> Vec<&'static CompletableToken> {
    let matches: Vec<&CompletableToken> = COMPLETABLE_TOKENS
        .iter()
        .filter(|token| token.lower.contains(&completion_text.text))
        .collect();
    if matches.is_empty() {
        COMPLETABLE_TOKENS
            .iter()
            .filter(|token| token.lower.contains(&completion_text.prefix))
            .collect()
    } else {
        matches
    }
}

/// Returns a completion response for the given text and position.
///
/// The `COMPLETABLE_TOKENS` list defines the tokens that can be completed.
/// A valid completion occurs when the prefix at the current position is
/// contained in a token from the `COMPLETABLE_TOKENS` list.
/// Comparisons are case-insensitive.
///
/// Returns `None` if the position is in a comment.
/// Returns the entire list if there is no prefix to complete.
pub fn get_completions(text: &str, position: Position) -> Option<CompletionResponse> {
    // No autocomplete in comments.
    let context = rms::document_context_at(text, position);
    if context.in_comment {
        return None;
    }

    // Note the empty string matches everything.
    let completion_text = rms::extract_autocomplete_prefix(text, position)?;
    let matches: Vec<&CompletableToken> = filter_tokens(&completion_text);
    let completion_items = matches
        .iter()
        .map(|token| token.to_completion_item(completion_text.range))
        .collect();
    Some(CompletionResponse::Array(completion_items))
}
