//! Handles hover requests for the language server.

use tower_lsp::lsp_types::{Hover, HoverContents, MarkupContent, MarkupKind, Position};

use crate::rms;

/// Returns a hover response for the given text and position.
pub fn get_hover(text: &str, position: Position) -> Option<Hover> {
    get_hover_text(text, position).map(|hover_text| Hover {
        contents: HoverContents::Markup(MarkupContent {
            kind: MarkupKind::Markdown,
            value: hover_text.to_string(),
        }),
        range: None,
    })
}

/// Returns the hover text for the token at the given position, or `None` if there is no text.
fn get_hover_text(text: &str, position: Position) -> Option<&'static str> {
    let context = rms::document_context_at(text, position);
    if context.in_comment {
        return None;
    }
    let token = rms::extract_token(text, position)?;
    lookup_hover(token)
}

// Generated by build.rs from data/hover.toml and data/hover_docs/.
// Defines: lookup_hover(name: &str) -> Option<&'static str>
include!(concat!(env!("OUT_DIR"), "/hover.rs"));
