//! Handles completion suggestions for Aoe2 RMS tokens.

use tower_lsp::lsp_types::{
    CompletionItem, CompletionItemKind, CompletionTextEdit, Documentation, InsertTextFormat,
    MarkupContent, MarkupKind, Range, TextEdit,
};

use crate::parser::hover::lookup_hover;

// Generated by build.rs from data/completions.toml.
// Defines: static COMPLETABLE_TOKENS: &[CompletableToken]
include!(concat!(env!("OUT_DIR"), "/completions.rs"));

/// A token that can be offered as a completion suggestion.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CompletableToken {
    /// The display label shown in the completion popup, with correct casing.
    label: &'static str,
    /// The lowercase version of the label, used for case-insensitive matching.
    lower: &'static str,
    /// The kind of token, used for coloring and icons in the completion popup.
    kind: CompletionItemKind,
    /// The snippet to insert when the completion is accepted, or `None` if the
    /// label should be inserted as-is. Uses LSP snippet syntax where `${N:placeholder}`
    /// marks tab stops and `$0` marks the final cursor position.
    snippet: Option<&'static str>,
}

impl CompletableToken {
    /// Creates a `CompletionItem` for this token.
    /// When the completion is accepted, `range` is replaced with the token's
    /// snippet if one exists, or the label otherwise.
    pub fn to_completion_item(&self, range: Range) -> CompletionItem {
        CompletionItem {
            label: self.label.to_string(),
            kind: Some(self.kind),
            insert_text_format: self.snippet.map(|_| InsertTextFormat::SNIPPET),
            text_edit: Some(CompletionTextEdit::Edit(TextEdit {
                range,
                new_text: self.snippet.unwrap_or(self.label).to_string(),
            })),
            documentation: lookup_hover(self.label).map(|doc| {
                Documentation::MarkupContent(MarkupContent {
                    kind: MarkupKind::Markdown,
                    value: doc.to_string(),
                })
            }),
            ..Default::default()
        }
    }
}

/// Returns the completable tokens matching the given completion text.
///
/// First attempts to match against the full token. If no matches are found,
/// falls back to matching against the prefix up to the cursor position.
/// This ensures that partially typed tokens that don't yet match anything
/// still surface relevant completions based on what has been typed so far.
///
/// For example, if the user types `create_xyz` with the cursor after `create_`,
/// the full token `"create_xyz"` matches nothing, but the prefix `"create_"`
/// matches all `create_` commands.
pub fn filter_tokens(completion_text: &CompletionText) -> Vec<&'static CompletableToken> {
    let matches: Vec<&CompletableToken> = COMPLETABLE_TOKENS
        .iter()
        .filter(|token| token.lower.contains(&completion_text.text))
        .collect();
    if matches.is_empty() {
        COMPLETABLE_TOKENS
            .iter()
            .filter(|token| token.lower.contains(&completion_text.prefix))
            .collect()
    } else {
        matches
    }
}

/// The result of extracting a completion text at a cursor position.
/// Note the returned token may be empty if the cursor's position is
/// within two consecutive whitespace characters.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CompletionText {
    /// The lowercase text to use for filtering completions.
    /// `token == &line[left..right]`, where `line` is the line of text
    /// containing the token.
    /// Empty when `left == right`.
    pub text: String,
    /// The prefix of the token up to the cursor position.
    /// All lowercase.
    /// Must be a prefix of `text`.
    pub prefix: String,
    /// The LSP range of the token in the document, used as the text edit range.
    pub range: Range,
}

impl CompletionText {
    /// Creates a `CompletionText` for the token spanning `[left, right)` in `text`,
    /// with the cursor at `cursor`.
    ///
    /// - `text`: the full document text.
    /// - `left`: byte offset of the token start, inclusive.
    /// - `cursor`: byte offset of the cursor position; must satisfy `left <= cursor <= right`.
    /// - `right`: byte offset of the token end, exclusive.
    /// - `range`: the LSP range of the token, used as the text edit range.
    ///
    /// `self.text` is set to the lowercase text of the full token `text[left..right]`.
    /// `self.prefix` is set to the lowercase text up to the cursor `text[left..cursor]`.
    pub fn new(text: &str, left: usize, cursor: usize, right: usize, range: Range) -> Self {
        debug_assert!(left <= cursor && cursor <= right);
        Self {
            text: text[left..right].to_lowercase(),
            prefix: text[left..cursor].to_lowercase(),
            range,
        }
    }
}
