//! Hover tooltip functionality for Aoe2 RMS files.

// Generated by build.rs from data/hover.toml and data/hover_docs/.
// Defines: lookup_hover(name: &str) -> Option<&'static str>
include!(concat!(env!("OUT_DIR"), "/hover.rs"));
